# Rutas de las Api
guikifix_api:
    resource: "@GuikifixApiBundle/Resources/config/routing.yml"
    prefix:   /
# Rutas de la presentación
guikifix_presentation:
    resource: "@GuikifixPresentationBundle/Resources/config/routing.yml"
    prefix:   /

###### RUTAS DE LOS BUNDLE ###########    
# Rutas de fos_user
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"