<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Guikifix\Core\Domain\JobTypeCategory;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
class Version20170221225648 extends AbstractMigration implements
    ContainerAwareInterface
{
    private $container;

    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    /**
     * @param Schema $schema
     */
    public function up(Schema $schema)
    {
        $em = $this->container->get('doctrine.orm.entity_manager');

        $rpJobTypeC = $em->getRepository('GuikifixDomain:JobTypeCategory');

        $data = json_decode('{"title":"Albañilería","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Construcción","lvl":2},{"title":"Colocación","lvl":2},{"title":"Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Demolición","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra:","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Presenta fisura","lvl":2},{"title":"Filtración","lvl":2},{"title":"Humedad","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Elemento","lvl":"3","child":[{"title":"Baño","lvl":4},{"title":"Habitación","lvl":4},{"title":"Accesorio de baño","lvl":4},{"title":"Pared","lvl":4},{"title":"Techo","lvl":4},{"title":"Accesorio de cocina","lvl":4},{"title":"Accesorio de fregadero","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Carpintería","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Fabricación","lvl":2},{"title":"Instalación","lvl":2},{"title":"Fabricación e Instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra:","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Lo desconozco","lvl":2},{"title":"No hay problema","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Elemento","lvl":"3","child":[{"title":"Biblioteca","lvl":4},{"title":"Closet","lvl":4},{"title":"Cocina","lvl":4},{"title":"Despensa","lvl":4},{"title":"Estantería","lvl":4},{"title":"Mueble","lvl":4},{"title":"Mueble de baño","lvl":4},{"title":"Puerta","lvl":4},{"title":"Techo de machihembrado","lvl":4},{"title":"Ventana","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Cerrajería","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2},{"title":"Auto","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e Instalación","lvl":2},{"title":"Apertura de cerradura","lvl":2},{"title":"Cambio de cerradura","lvl":2},{"title":"Cambio de combinación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Matenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de cerradura","lvl":1,"child":[{"title":"Convencional tipo cisa","lvl":2},{"title":"Seguridad Multilock","lvl":2},{"title":"Seguridad otros","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Dejé la llave adentro","lvl":2},{"title":"Cerradura atascada","lvl":2},{"title":"Abre con dificultad","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Drywall","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e Instalación","lvl":2},{"title":"Colocación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Moldura","lvl":4},{"title":"Pared Drywall","lvl":4},{"title":"Techo Drywall","lvl":4},{"title":"Techo cielo raso","lvl":4},{"title":"Yeso","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Electricidad","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Cableado","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Aire acondicionado","lvl":4},{"title":"Breaker","lvl":4},{"title":"Calentador de agua","lvl":4},{"title":"Campana eléctrica","lvl":4},{"title":"Luminaria","lvl":4},{"title":"Cocina Eléctrica","lvl":4},{"title":"Portón eléctrico/automatización","lvl":4},{"title":"Termotanque","lvl":4},{"title":"Toma corriente","lvl":4},{"title":"Toma especial","lvl":4},{"title":"Ventilador","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Fumigación","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Fumigación","lvl":2},{"title":"Otro","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Presenta rotura","lvl":2},{"title":"Bote de agua","lvl":2},{"title":"Poca presión","lvl":2},{"title":"No sale agua caliente","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Plaga","lvl":3,"child":[{"title":"Rastreros","lvl":4},{"title":"Ratas","lvl":4},{"title":"Ratones","lvl":4},{"title":"Voladores","lvl":4},{"title":"Otros","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Gasista","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Instalación","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"Fuga de Gas","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Calentador","lvl":4},{"title":"Cocina","lvl":4},{"title":"Detección de fuga","lvl":4},{"title":"Secadora","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"HadyMan","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Plomería","lvl":2},{"title":"Electricidad","lvl":2},{"title":"Albañilería","lvl":2},{"title":"Utilitario","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Herrería","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Fabricación","lvl":2},{"title":"Instalación","lvl":2},{"title":"Fabricación e Instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"Tipo de Elemento","lvl":1,"child":[{"title":"Decorativo","lvl":2},{"title":"Seguridad","lvl":2},{"title":"Constructivo","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Estructura","lvl":4},{"title":"Puerta","lvl":4},{"title":"Puerta entamborada","lvl":4},{"title":"Portón estacionamiento","lvl":4},{"title":"Reja","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Hidroneumaticos","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de instalación","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Funcionamiento irregular","lvl":2},{"title":"Bombas no prenden","lvl":2},{"title":"Bote de agua","lvl":2},{"title":"Poca presión","lvl":2},{"title":"No sale agua","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Impermeabilización","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Retiro y colocación","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"Area de Techo","lvl":1,"child":[{"title":"Hasta 50m2","lvl":2},{"title":"50m2 > 100m2","lvl":2},{"title":"100m2>200m2","lvl":2},{"title":"mas de 200m2","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Goteras","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Goteras","lvl":4},{"title":"Manto","lvl":4},{"title":"Pintura asfáltica","lvl":4},{"title":"Tejas","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Marmol, granito y piedras","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"Material","lvl":1,"child":[{"title":"Marmol","lvl":2},{"title":"Granito","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Baño","lvl":4},{"title":"Cocina","lvl":4},{"title":"Fachada","lvl":4},{"title":"Pared","lvl":4},{"title":"Piso","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Mudanza y transporte","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Mudanza","lvl":2},{"title":"Transporte","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Magnitud","lvl":1,"child":[{"title":"Parcial","lvl":2},{"title":"General","lvl":2}]},{"title":"Alcance","lvl":1,"child":[{"title":"Local","lvl":2},{"title":"Nacional","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Camión","lvl":1,"child":[{"title":"Cubierto","lvl":2},{"title":"Descubierto","lvl":2}]},{"title":"¿Necesita?","lvl":3,"child":[{"title":"Embalaje","lvl":4},{"title":"Carretillas","lvl":4},{"title":"Peones","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Toldos, persianas y puertas de baño","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Limpieza","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Funcionamiento irregular","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Persiana enrollable","lvl":4},{"title":"Persiana miniflex","lvl":4},{"title":"Persiana microflex","lvl":4},{"title":"Persiana vertical","lvl":4},{"title":"Toldo","lvl":4},{"title":"Toldo extensible","lvl":4},{"title":"Puerta plegable","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Pintura","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Pintura esmalte","lvl":2},{"title":"Pintura caucho","lvl":2},{"title":"Barnizado","lvl":2},{"title":"Laqueado","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Condición","lvl":1,"child":[{"title":"Nuevo","lvl":2},{"title":"Pintado","lvl":2}]},{"title":"Preparación de Superficie","lvl":1,"child":[{"title":"Encamisado","lvl":2},{"title":"Lijado y fondeado","lvl":2},{"title":"Lijado y sellado","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Aplicación","lvl":3,"child":[{"title":"Exterior","lvl":4},{"title":"Fachada","lvl":4},{"title":"Interior","lvl":4},{"title":"Laqueado de madera","lvl":4},{"title":"Rejas","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Pisos de madera","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"Tipo de piso","lvl":1,"child":[{"title":"Madera","lvl":2},{"title":"Parquet","lvl":2},{"title":"Laminado o Flotante","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Plantas electricas","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro Instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Instalación","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"¿Capacidad?","lvl":1,"child":[{"title":"< 10 KVA","lvl":2},{"title":"10 KVA a 50 KVA","lvl":2},{"title":"50 KVA a 100 KVA","lvl":2},{"title":"> 100 KVA","lvl":2},{"title":"Lo desconozco","lvl":2}]},{"title":"¿Transfer Switch?","lvl":1,"child":[{"title":"Manual","lvl":2},{"title":"Automático","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"No","lvl":2}]},{"title":"¿Combustible?","lvl":1,"child":[{"title":"Diesel","lvl":2},{"title":"Gas","lvl":2},{"title":"Gasolina","lvl":2},{"title":"Lo desconozco","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Plomería","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Destapado","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Rotura","lvl":2},{"title":"Bote de agua","lvl":2},{"title":"Poca presión","lvl":2},{"title":"No sale agua caliente","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Bañera","lvl":4},{"title":"Batea","lvl":4},{"title":"Bidet","lvl":4},{"title":"Canilla","lvl":4},{"title":"Cañería","lvl":4},{"title":"Ducha","lvl":4},{"title":"Fregadero","lvl":4},{"title":"Grifería","lvl":4},{"title":"Inodoro","lvl":4},{"title":"Lavamanos","lvl":4},{"title":"Llaves de paso","lvl":4},{"title":"Sifón","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Seguridad y prevención","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de Instalación","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Alarma contra robo","lvl":4},{"title":"Cerco eléctrico","lvl":4},{"title":"CCTV","lvl":4},{"title":"Control de acceso","lvl":4},{"title":"Intercomunicador","lvl":4},{"title":"Sistema detección de incendio","lvl":4},{"title":"Video portero","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Técnico de aire acondicionado","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Sustitución","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Instalación de Ducteria pata distribución","lvl":2},{"title":"Recarga de gas","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Condición","lvl":1,"child":[{"title":"Nuevo","lvl":2},{"title":"Usado","lvl":2}]},{"title":"Tipo de equipo","lvl":1,"child":[{"title":"Ventana","lvl":2},{"title":"Split","lvl":2},{"title":"Multi Split","lvl":2},{"title":"Central","lvl":2}]},{"title":"Capacidad","lvl":1,"child":[{"title":"9.000 BTU","lvl":2},{"title":"12.000 BTU","lvl":2},{"title":"18.000 BTU","lvl":2},{"title":"24.000 BTU","lvl":2},{"title":"Otro","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"No enfría","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Técnico de computadoras","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro Instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Condición","lvl":1,"child":[{"title":"Nuevo","lvl":2},{"title":"Usado","lvl":2}]},{"title":"Area","lvl":1,"child":[{"title":"Sistema Operativo","lvl":2},{"title":"Equipo","lvl":2},{"title":"Programa","lvl":2},{"title":"Red Wifi","lvl":2},{"title":"Impresora / Scanner","lvl":2},{"title":"Monitor","lvl":2},{"title":"Desktop","lvl":2},{"title":"Laptop","lvl":2},{"title":"Otro","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"No hay conexión a Internet","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]},{"title":"Elemento","lvl":3,"child":[{"title":"Cableado estructurado","lvl":4},{"title":"CPU","lvl":4},{"title":"Desktop","lvl":4},{"title":"Impresora / Scanner","lvl":4},{"title":"Laptop","lvl":4},{"title":"Monitor","lvl":4},{"title":"Red Wifi","lvl":4},{"title":"Sistema operativo","lvl":4},{"title":"Software","lvl":4},{"title":"Otro","lvl":4}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Técnico de electrodomésticos","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Condición","lvl":1,"child":[{"title":"Nuevo","lvl":2},{"title":"Usado","lvl":2}]},{"title":"Tipo de equipo","lvl":1,"child":[{"title":"Lavadora","lvl":2},{"title":"Secadora","lvl":2},{"title":"Nevera","lvl":2},{"title":"Horno","lvl":2},{"title":"Microonda","lvl":2},{"title":"Lavaplatos","lvl":2},{"title":"Televisión","lvl":2},{"title":"Otro","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"No funciona","lvl":2},{"title":"Funcionamiento irregular","lvl":2},{"title":"No calienta / No enfría","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

        $data = json_decode('{"title":"Vidrios","lvl":0,"child":[{"title":"Tipo de Inmueble","lvl":1,"child":[{"title":"Casa","lvl":2},{"title":"Apartamento","lvl":2},{"title":"Edificio","lvl":2},{"title":"Oficina","lvl":2},{"title":"Comercio","lvl":2},{"title":"Industria","lvl":2}]},{"title":"Tipo de Servicio","lvl":1,"child":[{"title":"Suministro","lvl":2},{"title":"Instalación","lvl":2},{"title":"Suministro e instalación","lvl":2},{"title":"Reparación","lvl":2},{"title":"Revisión","lvl":2},{"title":"Mantenimiento","lvl":2},{"title":"Trabajo de Vidrieras","lvl":2},{"title":"Otro","lvl":2}]},{"title":"Tipo de obra","lvl":1,"child":[{"title":"Nueva","lvl":2},{"title":"Existente","lvl":2}]},{"title":"¿Cuál es el Problema?","lvl":1,"child":[{"title":"Vidrio roto","lvl":2},{"title":"Mecanismo atascado","lvl":2},{"title":"No rueda / No abre","lvl":2},{"title":"Lo desconozco","lvl":2},{"title":"Otro","lvl":2},{"title":"No hay problema","lvl":2}]}]}',true);
        $rpJobTypeC->save($this->createCategory($data));

    }

    /**
     * @param Schema $schema
     */
    public function down(Schema $schema)
    {
        // this down() migration is auto-generated, please modify it to your needs

    }

    private function createCategory($data)
    {
        $jobTypeC = new JobTypeCategory();
        $jobTypeC->setTitle($data['title']);
        $jobTypeC->setLvl($data['lvl']);

        if (isset($data['child']))
            foreach ($data['child'] as $key => $currentChild) {
                $child = $this->createCategory($currentChild);
                $child->setParent($jobTypeC);
                $jobTypeC->addChild($child);
            }

        return $jobTypeC;
    }
}