# Manejo para el persisttir presupuesto.
guikifix_api_set_job:
    path:     /set
    defaults: { _controller: GuikifixApiBundle:User\Job:statusCategories }
    methods: POST

# Manejo del listado de presupuesto.
guikifix_api_get_job_list:
    path:     /get/list
    defaults: { _controller: GuikifixApiBundle:User\Job:getListJobs }
    methods: POST