Guikifix\Core\Domain\Document:
    type: entity
    table: document
    repositoryClass: Guikifix\ApiBundle\Repository\DocumentRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # Comentario
      filaname:
        type: string
      # Calidad
      name:
        type: string