Guikifix\Core\Domain\Document:
    type: entity
    table: document
    repositoryClass: Guikifix\ApiBundle\Repository\DocumentRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # path del archivo
      filaname:
        type: string
      # Nombre adicional del archivo
      name:
        type: string
      # Tipo de archivo, fichero imagenes
      type:
        type: integer


    manyToOne:
      # ubicación del trabajo
        job:
            targetEntity: Guikifix\Core\Domain\Job
            inversedBy: documents
            joinColumn:
                name: job_id
                referencedColumnName: id
            orphanRemoval: false