Guikifix\Core\Domain\JobStatusCategory:
    type: entity
    table: job_status_category
    repositoryClass: Guikifix\ApiBundle\Repository\JobStatusCategoryRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # Título del trabajo
      title:
        type: string
      # Pregunta que se le realiza al cliente
      subtitle:
        type: string
      # Nivel en el arbol
      lvl:
        type: integer
      # Ultima actualización
      last_update:
        type: datetime
      # Fecha de creación
      created:
        type: datetime

    oneToMany:
      # Categorias hijas
      children:
          targetEntity: Guikifix\Core\Domain\JobStatusCategory
          mappedBy: parent
          orderBy:
              title: ASC
          cascade: ["persist"]
    manyToOne:
      # Category padre
      parent:
          targetEntity: Guikifix\Core\Domain\JobStatusCategory
          inversedBy: children
          joinColumns:
              parent_id:
                  referencedColumnName: id
          orphanRemoval: false

    manyToMany:
      # Estado posible del trabajo
      jobs_status:
          targetEntity: Job
          cascade: {  }
          mappedBy: jobs_status_category