Guikifix\Core\Domain\Message:
    type: entity
    table: message
    repositoryClass: Guikifix\ApiBundle\Repository\MessageRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # Comentario o mensaje enviado
      comment:
        type: string
      # status del mensaje
      # 0 : No leido
      # 1 : Leido
      status:
        type: integer
      # Ultima actualización
      last_update:
        type: datetime
      # Fecha de creación
      created:
        type: datetime
    
    manyToOne:
        # Usuario que crea un mensaje
        transmitter:
          targetEntity: Guikifix\ApiBundle\Entity\User
          inversedBy: msg_transmiter
          joinColumn:
              name: transmitter_user_id
              referencedColumnName: id
          cascade: ["persist"]
        # Usuario que crea un mensaje
        receiver:
          targetEntity: Guikifix\ApiBundle\Entity\User
          inversedBy: msg_receiver
          joinColumn:
              name: receiver_user_id
              referencedColumnName: id
          cascade: ["persist"]
        # Presupuesto 
        budget:
          targetEntity: Guikifix\Core\Domain\Budget
          inversedBy: messages
          joinColumn:
            budget_id:
              referencedColumnName: id
          cascade: ["persist"]