Guikifix\Core\Domain\UserProfile:
    type: entity
    table: user_profile
    repositoryClass: Guikifix\ApiBundle\Repository\UserProfileRepository

    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
      # Nombre del usuario
      first_name:
        type: string
      # Apellido
      last_name:
        type: string
      # Celular 
      cell_phone:
        type: string
      # Teléfono fijo
      phone:
        type: string
        nullable: true
      # Fecha de nacimiento
      birthdate:
        type: date
        nullable: true
      # Género
      gender:
        type: integer
        nullable: true
      # Como nos contactaste
      how_contact_us:
        type: string
        nullable: true
      # Codigo Referido
      core_refered:
        type: string
        nullable: true
      # Ultima actualización
      last_update:
        type: datetime
      # Fecha de creación
      created:
        type: datetime

    oneToOne:
      # Usuario relacionado al perfil  
      user:
          targetEntity: Guikifix\ApiBundle\Entity\User
          inversedBy: user_profile
          joinColumn:
              user_id:
                  referencedColumnName: id
          cascade: ["persist"]
    oneToMany:
        # Trabajos relacionado al perdil
        jobs:
            targetEntity: Guikifix\Core\Domain\Job
            mappedBy: user_profile
            cascade: ["persist"]
        # Calificaciones emitidas por el usuario
        qualifications:
            targetEntity: Guikifix\Core\Domain\Qualification
            mappedBy: user_profile
            cascade: ["persist"]

    manyToOne:
      # ubicación del usuario
      location:
            targetEntity: Guikifix\Core\Domain\Location
            mappedBy: null
            joinColumns:
                location_id:
                    referencedColumnName: id
            orphanRemoval: false